# **Solemne 1 — Minería de Datos 2026**

# 1.- Obtencion de datos
## ¿qué espero encontrar?
En la tabla de 'health_nutrition_population' espero encontrar referencias a la salud nutricional de la poblacion en algun pais/ciudad especificado en la tabla.

In [22]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project="yo-si-489418")

dataset_ref = client.dataset("world_bank_health_population", project="bigquery-public-data") #Dentro del la bigquery publica, busca el proyecto del banco mundial

tables = list(client.list_tables(dataset_ref))

table_ref = dataset_ref.table("health_nutrition_population")

query = """
SELECT *
FROM `bigquery-public-data.world_bank_health_population.health_nutrition_population`
ORDER BY year DESC
"""


dry_run_config = bigquery.QueryJobConfig(dry_run=True)

dry_run_query_job = client.query(query, job_config=dry_run_config) #Estas lineas de codigo me mostraran cuando pesaran los datos que estare consultando.

print()
print("This query will process {} bytes.".format(dry_run_query_job.total_bytes_processed))



safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10) #Esto limita la cantidad de bytes que podria procesar (quizas no necesario pero no esta de mas)
query_job = client.query(query, job_config=safe_config)


Pandass = query_job.to_dataframe()       #transforma la query a un dataframe de pandas

Pandass

c:\Users\joshe\Documents\U weas\GIT\venv\Lib\site-packages\google\auth\_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

This query will process 310099813 bytes.

,country_name,country_code,indicator_name,indicator_code,value,year
0,Belarus,BLR,"Population ages 70-74, male (% of male populat...",SP.POP.7074.MA.5Y,2.252892,2020
1,Other small states,OSS,"Population ages 05-09, female (% of female pop...",SP.POP.0509.FE.5Y,10.482102,2020
2,Vietnam,VNM,"Population ages 35-39, male",SP.POP.3539.MA,1.000000,2020
3,Indonesia,IDN,People with basic handwashing facilities inclu...,SH.STA.HYGN.ZS,94.107068,2020
4,New Zealand,NZL,"Population ages 05-09, male",SP.POP.0509.MA,1.000000,2020
...,...,...,...,...,...,...
3174991,Lesotho,LSO,"Age population, age 18, male, interpolated",SP.POP.AG18.MA.IN,1.000000,1960
3174992,Malaysia,MYS,"Age population, age 02, female, interpolated",SP.POP.AG02.FE.IN,1.000000,1960
3174993,Gibraltar,GIB,Rural population (% of total population),SP.RUR.TOTL.ZS,1.000000,1960
3174994,Mozambique,MOZ,"Age population, age 04, female, interpolated",SP.POP.AG04.FE.IN,1.000000,1960
3174995,"Yemen, Rep.",YEM,"Population ages 65-69, female",SP.POP.6569.FE,1.000000,1960

# Analisis de Datos

---

Primero dare los datos pedidos como outpout de codigo sin filtrar y luego el filtrado de datos para trabajar de forma eficiente

In [76]:
print(f"Filas: {Pandass.shape[0]:,} | Columnas: {Pandass.shape[1]}")
print("Tipos:", ", ".join([f"{col}: {dtype}" for col, dtype in Pandass.dtypes.items()]))
print(f"Rango temporal: {Pandass['year'].min()} - {Pandass['year'].max()}")

nulos = Pandass.isnull().sum()
print("Nulos:", ", ".join([f"{col}: {val:,}" for col, val in nulos.items()]))

Filas: 84,879 | Columnas: 4
Tipos: country_name: object, indicator_name: object, value: float64, year: Int64
Rango temporal: 2000 - 2020
Nulos: country_name: 0, indicator_name: 0, value: 0, year: 0

---
Ahora hare un diccionario con los paises de latinoamerica para filtrar despues
, ya que este es un lugar mas cercano y mas de interes que paises de otro continente o que hablen otro idioma (por el entendimiento mas que nada)

In [39]:
latam = [
    'Argentina', 'Bolivia', 'Brasil', 'Chile', 'Colombia',
    'Costa Rica', 'Cuba', 'Ecuador', 'El Salvador', 'Guatemala',
    'Honduras', 'México', 'Nicaragua', 'Panamá', 'Paraguay',
    'Perú', 'República Dominicana', 'Uruguay', 'Venezuela'
]

Luego usare varios filtros y descartaremos algunas columnas, por ejemplo descartaremos 'country_code' y 'indicator_code' ya que esto no nos entrega datos relevantes para el analisis.

Tambien filtraremos los años, donde se veran los datos tomas entre los años 2000 y 2020, esto porque pienso que los datos atras del 2000 pueden verse afectados debido a la falta de tecnologia y concexion que pudo haber en años posteriores

In [71]:
Pandass_act = Pandass[['country_name', 'indicator_name', 'value', 'year']]
Pandass_act = Pandass_act[(Pandass_act['year'].between(2000, 2020) & Pandass_act['country_name'].isin(latam))]


print(Pandass_act['country_name'].unique())
print()
print(f"Filas: {Pandass_act.shape[0]:,} | Columnas: {Pandass_act.shape[1]}")
print("Tipos:", ", ".join([f"{col}: {dtype}" for col, dtype in Pandass_act.dtypes.items()]))
print(f"Rango temporal: {Pandass_act['year'].min()} - {Pandass_act['year'].max()}")

nulos = Pandass_act.isnull().sum()
print("Nulos:", ", ".join([f"{col}: {val:,}" for col, val in nulos.items()]))

['El Salvador' 'Ecuador' 'Guatemala' 'Nicaragua' 'Colombia' 'Argentina'
 'Bolivia' 'Cuba' 'Uruguay' 'Chile' 'Costa Rica' 'Honduras' 'Paraguay']

Filas: 84,879 | Columnas: 4
Tipos: country_name: object, indicator_name: object, value: float64, year: Int64
Rango temporal: 2000 - 2020
Nulos: country_name: 0, indicator_name: 0, value: 0, year: 0

Viendo estos datos los cuales fueron filtrado a datos mas actuales (Del 2000 en adelante) esto para tener una mayor fiabilidad en la compilacion de estos (tambien porque no existen nulos), espero que tengan una calidad decente para poder analisarlos de forma optima. Con un alcance directamente sobre la poblacion latinoamerica, donde busco la tasa de mortalidad en suicidios en hombres y mujeres., como la cantidad de filas no es tan grande podria ser que los datos a analizar no nos den una estadistica muy correcta.

---

Entonces ahora hare un filtro donde el las columnas 'indicator_name' tengan la palabra 'suicide'

In [82]:
suicidios = Pandass_act[Pandass_act['indicator_name'].str.contains('suicide', case=False, na=False)]

#Uso todos estos datos para separar el termino suicidio dentro de la columna "indicator_name"

suicidios = suicidios.copy()            #me arrojaba un warning asi que con esto pude solucionarlo...

def normalizar(x):
    return (x - x.min()) / (x.max() - x.min())                  #funcion para normalizar los valores de la tabla

suicidios['valores_norma'] = suicidios.groupby('country_name')['value'].transform(normalizar)

suicidios = suicidios.sort_values(['country_name', 'year'])
suicidios

,country_name,indicator_name,value,year,valores_norma
1382616,Argentina,"Suicide mortality rate, male (per 100,000 male...",15.2,2000,0.893082
1386129,Argentina,"Suicide mortality rate, female (per 100,000 fe...",3.4,2000,0.150943
1401605,Argentina,"Suicide mortality rate (per 100,000 population)",9.1,2000,0.509434
1292967,Argentina,"Suicide mortality rate, male (per 100,000 male...",16.9,2001,1.000000
1297674,Argentina,"Suicide mortality rate (per 100,000 population)",10.3,2001,0.584906
...,...,...,...,...,...
151931,Uruguay,"Suicide mortality rate (per 100,000 population)",21.2,2018,0.599407
165786,Uruguay,"Suicide mortality rate, male (per 100,000 male...",34.7,2018,1.000000
58736,Uruguay,"Suicide mortality rate (per 100,000 population)",21.2,2019,0.599407
70079,Uruguay,"Suicide mortality rate, male (per 100,000 male...",34.5,2019,0.994065
84044,Uruguay,"Suicide mortality rate, female (per 100,000 fe...",8.9,2019,0.234421

In [91]:
dic_paises = {}
for pais in suicidios["country_name"].unique():
    dic_paises[pais] = suicidios[suicidios["country_name"] == pais]
    print(f"{pais}: {len(dic_paises[pais])} filas")


tabla_hori = pd.DataFrame({pais: dic_paises[pais]['valores_norma'].values for pais in dic_paises})

tabla_hori

Argentina: 60 filas
Bolivia: 60 filas
Chile: 60 filas
Colombia: 60 filas
Costa Rica: 60 filas
Cuba: 60 filas
Ecuador: 60 filas
El Salvador: 60 filas
Guatemala: 60 filas
Honduras: 60 filas
Nicaragua: 60 filas
Paraguay: 60 filas
Uruguay: 60 filas

,Argentina,Bolivia,Chile,Colombia,Costa Rica,Cuba,Ecuador,El Salvador,Guatemala,Honduras,Nicaragua,Paraguay,Uruguay
0,0.893082,0.000000,0.862245,0.984848,0.786260,0.686441,0.375000,0.363636,0.145349,0.406250,0.902778,0.168831,0.774481
1,0.150943,0.756410,0.096939,0.242424,0.412214,0.372881,0.520833,0.566434,0.941860,0.203125,0.361111,0.376623,0.000000
2,0.509434,0.474359,0.474490,0.000000,0.038168,1.000000,0.229167,0.167832,0.534884,0.000000,0.625000,0.272727,0.136499
3,1.000000,0.987179,0.862245,0.984848,0.320611,0.309322,0.569444,0.405594,0.000000,0.203125,0.319444,0.272727,0.400593
4,0.584906,0.448718,0.096939,0.227273,0.603053,0.605932,0.250000,0.188811,0.162791,0.406250,0.583333,0.194805,0.157270
5,0.000000,0.717949,0.474490,0.590909,0.038168,0.902542,0.409722,0.000000,0.563953,0.000000,0.847222,0.337662,0.658754
6,0.981132,0.461538,0.438776,0.560606,0.832061,0.313559,0.284722,0.153846,0.552326,0.406250,0.263889,0.285714,0.000000
7,0.201258,0.717949,0.000000,0.212121,0.000000,0.851695,0.673611,0.300699,0.168605,0.000000,0.000000,0.376623,0.557864
8,0.578616,0.961538,0.790816,0.924242,0.000000,0.580508,0.479167,0.461538,0.953488,0.203125,0.875000,0.337662,0.219585
9,0.937107,0.448718,0.443878,0.545455,0.526718,0.542373,0.743056,0.160839,0.168605,0.218750,0.638889,0.311688,0.181009
10,0.547170,0.948718,0.801020,0.227273,0.122137,0.245763,0.520833,0.000000,0.982558,0.015625,1.000000,0.155844,0.703264
11,0.176101,0.692308,0.000000,0.863636,0.000000,0.834746,0.291667,0.384615,0.569767,0.421875,0.000000,0.467532,0.433234
12,0.163522,0.435897,0.107143,0.530303,0.099237,0.546610,0.000000,0.405594,0.000000,0.203125,0.986111,0.584416,0.160237
13,0.830189,0.679487,0.464286,0.878788,0.541985,0.250000,0.319444,0.118881,0.000000,0.406250,0.611111,0.246753,0.709199
14,0.484277,0.910256,0.836735,0.181818,0.984733,0.000000,0.791667,0.713287,1.000000,0.015625,0.250000,0.415584,0.424332
15,0.811321,0.000000,0.780612,0.818182,0.000000,0.504237,0.618056,0.125874,0.000000,0.218750,0.180556,0.545455,0.409496
16,0.163522,0.448718,0.443878,0.469697,0.770992,0.233051,0.326389,0.475524,0.000000,0.406250,0.583333,0.324675,0.664688
17,0.477987,0.679487,0.112245,0.000000,0.427481,0.779661,0.000000,0.846154,0.604651,0.015625,1.000000,0.441558,0.169139
18,0.477987,0.410256,0.122449,0.818182,1.000000,0.495763,0.000000,0.000000,0.168605,0.406250,0.152778,0.415584,0.201780
19,0.144654,0.628205,0.811224,0.469697,0.564885,0.822034,0.000000,0.391608,0.982558,0.015625,0.500000,0.220779,0.673591
20,0.830189,0.846154,0.000000,0.136364,0.137405,0.173729,0.000000,0.748252,0.563953,0.218750,0.861111,0.623377,0.430267
21,0.459119,0.653846,0.000000,0.469697,0.641221,0.474576,0.638889,0.111888,0.424419,0.203125,0.194444,0.207792,0.210682
22,0.786164,0.858974,0.163265,0.833333,0.358779,0.779661,0.951389,0.895105,0.715116,0.015625,0.888889,0.363636,0.486647
23,0.144654,0.448718,0.000000,0.136364,0.068702,0.000000,0.326389,0.482517,0.145349,0.406250,0.541667,0.000000,0.786350
24,0.836478,0.435897,0.571429,0.848485,0.045802,0.203390,0.326389,0.405594,0.000000,0.000000,0.250000,0.493506,0.688427
25,0.484277,0.833333,0.964286,0.484848,0.343511,0.504237,0.659722,0.734266,0.691860,0.203125,0.888889,0.337662,0.418398
26,0.144654,0.000000,0.193878,0.121212,0.641221,0.000000,1.000000,0.111888,0.133721,0.390625,0.569444,0.168831,0.166172
27,0.465409,0.435897,0.596939,0.833333,0.351145,0.538136,0.659722,0.104895,0.401163,0.031250,0.847222,0.675325,0.000000
28,0.138365,0.000000,0.000000,0.469697,0.061069,0.860169,0.319444,0.531469,0.668605,0.000000,0.000000,0.441558,0.145401
29,0.811321,0.846154,1.000000,0.121212,0.648855,0.220339,0.993056,1.000000,0.145349,0.375000,0.000000,0.194805,0.703264
30,0.138365,0.000000,0.540816,0.787879,0.450382,0.567797,0.923611,0.083916,0.610465,0.375000,0.875000,0.324675,0.183976
31,0.830189,0.435897,0.173469,0.424242,0.000000,0.216102,0.312500,0.664336,0.127907,0.031250,0.527778,0.493506,0.724036
32,0.477987,0.858974,0.923469,0.075758,0.824427,0.927966,0.618056,0.356643,0.366279,0.000000,0.180556,0.155844,0.000000
33,0.000000,0.871795,0.163265,0.742424,0.106870,0.911017,0.611111,0.125874,0.000000,0.000000,0.986111,0.467532,0.189911
34,0.144654,0.435897,0.938776,0.075758,0.450382,0.555085,0.298611,0.902098,0.540698,0.171875,0.625000,0.220779,0.768546
35,0.471698,0.653846,0.545918,0.409091,0.793893,0.207627,0.923611,0.000000,0.325581,0.359375,0.263889,0.701299,0.468843
36,0.509434,0.423077,0.841837,0.075758,0.778626,0.902542,0.631944,0.713287,0.296512,0.390625,0.208333,0.636364,0.498516
37,0.886792,0.858974,0.484694,0.787879,0.427481,0.542373,0.291667,0.405594,0.488372,0.781250,0.472222,0.285714,0.181009
38,0.157233,0.000000,0.142857,0.424242,0.068702,0.186441,0.000000,0.118881,0.110465,0.000000,0.750000,0.467532,0.842730
39,0.830189,0.858974,0.775510,0.742424,0.061069,0.546610,0.916667,0.097902,0.000000,0.000000,0.208333,0.506494,0.715134
40,0.477987,0.000000,0.448980,0.409091,0.435115,0.194915,0.270833,0.685315,0.110465,0.375000,0.597222,0.000000,0.439169
41,0.138365,0.423077,0.132653,0.075758,0.816794,0.906780,0.597222,0.377622,0.284884,0.765625,0.986111,0.233766,0.183976
42,0.886792,0.435897,0.785714,0.787879,0.641221,0.525424,0.541667,0.335664,0.453488,0.000000,0.819444,0.363636,0.204748
43,0.169811,0.000000,0.127551,0.424242,0.351145,0.860169,0.243056,0.118881,0.279070,0.406250,0.486111,0.636364,0.789318
44,0.522013,0.666667,0.454082,0.060606,0.068702,0.199153,0.000000,0.573427,0.110465,0.828125,0.166667,0.883117,0.486647
45,0.792453,0.692308,0.000000,0.833333,0.778626,0.911017,0.854167,0.083916,0.110465,0.000000,0.166667,0.935065,0.198813
46,0.144654,0.935897,0.000000,0.136364,0.099237,0.194915,0.541667,0.790210,0.279070,0.031250,0.444444,0.285714,0.872404
47,0.459119,0.435897,0.158163,0.469697,0.435115,0.000000,0.229167,0.412587,0.459302,1.000000,0.736111,0.610390,0.522255
48,0.798742,1.000000,0.000000,0.893939,0.511450,0.525424,0.000000,0.090909,0.273256,0.375000,0.472222,0.558442,0.255193
49,0.132075,0.448718,0.122449,0.090909,0.099237,0.864407,0.875000,0.328671,0.104651,0.000000,0.111111,0.870130,0.596439
50,0.459119,0.717949,0.806122,0.484848,0.000000,0.186441,0.229167,0.601399,0.447674,0.031250,0.000000,0.233766,0.964392
51,0.496855,0.692308,0.739796,0.560606,0.389313,0.572034,0.909722,0.664336,0.441860,0.000000,0.805556,0.311688,0.973294
52,0.157233,0.961538,0.423469,1.000000,0.679389,0.927966,0.229167,0.356643,0.098837,0.390625,0.152778,0.987013,0.225519
53,0.849057,0.423077,0.112245,0.136364,0.099237,0.224576,0.569444,0.090909,0.267442,0.203125,0.472222,0.662338,0.587537
54,0.163522,0.679487,0.693878,0.000000,0.091603,0.563559,0.201389,0.083916,0.488372,0.390625,0.166667,0.987013,0.225519
55,0.886792,0.948718,0.397959,0.106061,0.473282,0.919492,0.493056,0.657343,0.000000,0.000000,0.000000,0.285714,0.599407
56,0.515723,0.410256,0.112245,0.818182,0.854962,0.207627,0.777778,0.000000,0.093023,0.031250,0.486111,0.000000,1.000000
57,0.798742,0.666667,0.112245,0.772727,0.541985,0.572034,0.180556,0.356643,0.284884,0.203125,0.125000,0.000000,0.599407
58,0.465409,0.948718,0.709184,0.439394,0.000000,0.000000,0.458333,0.664336,0.093023,0.390625,0.472222,0.285714,0.994065
59,0.144654,0.397436,0.000000,0.121212,1.000000,0.000000,0.736111,0.076923,0.488372,0.000000,0.819444,1.000000,0.234421